### ISSUE TITLE
No output produced by run_inference.sh

### ISSUE THREAD

**Issue by al979** [Kuhlman-Lab/PIPPack#2]
Thank you for producing this convenient and efficient tool!

When I run run_inference.sh, I receive the following output and no error messages:

`
Loading checkpoint from /home/al979/Khare/PIPPack/model_weights/pippack_model_1_ckpt.pt
	Epoch 286
`

An empty directory named `pippack_output` is also created, but no output files are generated within this directory.
The run completes without generating any error messages, but it seems to not be generating the output files. 

I did do a recursive regular expression search (grep -r "kuhl") to find any paths that I needed to change to the appropriate ones for my directory and changed these appropriately. 

Could you provide some guidance on how to resolve this issue?
Any advice would be greatly appreciated!

**Comment by nzrandol** [comment]
Thanks for your interest in PIPPack! I'm happy to help.

My best guess is that the `inference.py` script isn't finding any PDBs. Line 153 
(`pdb_files = glob.glob(os.path.join(cfg.inference.pdb_path, '*.pdb'))`) should be searching for the PDBs containing the proteins you want to pack, so I'd make sure that `inference.pdb_path` in `run_inference.sh` is pointing to the right spot. You could also make sure that the `pdb_files`, `proteins`, and `batches` variables in `inference.py` aren't empty by adding some print statements to the code.

Hope that helps!
Nick

**Comment by al979** [comment]
Thank you so much! I was able to resolve the issue with your guidance!
